# Load ~/.extra, ~/.bash_prompt, ~/.exports, ~/.aliases and ~/.functions
# ~/.extra can be used for settings you don’t want to commit
for file in ~/.{extra,bash_prompt,exports,aliases,functions}; do
	[ -r "$file" ] && source "$file"
done
unset file

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

PATH=/usr/local/bin:$PATH
PATH=$PATH:/usr/bin
## Add RVM to PATH for scripting
# PATH=$PATH:$HOME/.rvm/bin
#PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
## Postgres App
# PATH="/Applications/Postgres.app/Contents/MacOS/bin:$PATH"
