#!/usr/bin/env ruby

require 'rainbow/ext/string'
require 'json'

require_relative "lib/front_lines"

VERSION = 1

config = File.join(ENV['HOME'], '.wdi-installfest/wdi_help/config/wdi_info.yaml')
WDI_INFO = YAML::load(File.open(config))

OPTIONS = [
    "Instructors", 
    "Producers", 
    "Building Locations and Hours", 
    "Office Hours",
    "I'm sick today"
]

loop do
  choice = menu
  case choice
  when 0 then tell_me_about(:instructors)
  when 1 then tell_me_about(:producers)
  when 2 then tell_me_about(:locations)
  when 3 then tell_me_about(:office_hours)
  when 4 then alert_instructors
  end
  continue?
end

# Resources

# https://github.com/hipchat/hipchat-rb
# https://github.com/peter-murach/github
# https://api.hipchat.com/v1/rooms/message
# http://help.hipchat.com/knowledgebase/articles/64389-github-integration

# Symlinked with 
# ln -s "/Users/philco/.wdi-installfest/wdi_help" /usr/local/bin/wdi_help